nav:
    - Project:
      - LEAP Architecture: index.md
      # - Plans & Priorities: project-plans.md
      - Minutes & Notes: project-minutes.md
    - Domains: 
      - Kitchen: domain-kitchen.md
      - Grocery: domain-grocery.md
      - Logistics: domain-logistics.md
      # - Restaurant: domain-restaurant.md
      # - Housework: domain-housework.md
    - Experiments: 
      - Num of Objects: exp-objects.md
      - All Egg Recipes: exp-egg-recipes.md
      - Two Dishes: exp-two-dishes.md
      - Customers Happy: exp-customer-happy.md
      # - Num of Goal Predicates: exp-goals.md
      # - Num of Operators: exp-operators.md
    - Set it up: 
      - Set up the Repository: setup-repository.md
      - Set up MkDocs: setup-mkdocs.md
      - Editor's Notes: setup-notes.md

site_name: LEAPdocs
theme: readthedocs
# theme:
#     name: null
#     custom_dir: '/miniconda3/lib/python3.7/site-packages/mkdocs/themes/readthediary/'

site_favicon: css/favicon.ico
extra_css: [css/extra.css]
markdown_extensions:
    - toc:
        permalink: "#"
