nav:
    - Project:
      - LEAP Architecture: index.md
      - Test Runs [ NEW ]: project-test.md
      # - Plans & Priorities: project-plans.md
      - Minutes & Notes: project-minutes.md
    - Domains: 
      - Grocery - action costs [ NEW ]: domain-grocery.md
      - Kitchen - large universe: domain-kitchen.md
      ## - Logistics: domain-logistics.md
      # - Restaurant: domain-restaurant.md
      # - Housework: domain-housework.md
    - Experiments: 
      - Num of Goal Predicates [ NEW ]: exp-goals.md
      - Num of Objects: exp-objects.md
      - All Egg Recipes: exp-egg-recipes.md
      - Two Dishes [ NEW ]: exp-two-dishes.md
      - Satisfising v.s. Optimizing [ NEW ]: exp-planner-options.md
      - Merged Domains [ NEW ]: exp-merged-domains.md
    - Notes:
      - FastDownward [ NEW ]: notes-fd.md
    - Set it up: 
      - Set up the Repository: setup-repository.md
      - Set up MkDocs: setup-mkdocs.md
      - Editor's Notes: setup-notes.md

site_name: LEAPdocs
theme: readthedocs
# theme:
#     name: null
#     custom_dir: '/miniconda3/lib/python3.7/site-packages/mkdocs/themes/readthediary/'

site_favicon: css/favicon.ico
extra_css: [css/extra.css]
markdown_extensions:
    - toc:
        permalink: "#"
